# Generated by Django 4.0.4 on 2022-12-07 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billings', '0004_alter_cart_user_alter_product_user_alter_store_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('imgUrl', models.TextField(default='')),
                ('selling_price', models.FloatField(default=1)),
                ('actual_price', models.FloatField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
