# Generated by Django 4.0.4 on 2022-12-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
