# Generated by Django 4.0.4 on 2022-11-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='department_name',
        ),
    ]
