# Generated by Django 4.0.4 on 2022-11-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='department',
        ),
        migrations.AddField(
            model_name='account',
            name='market',
            field=models.CharField(default='market', max_length=30, unique=True),
        ),
    ]
