# Generated by Django 4.0.4 on 2022-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
