name: Deploy to EC2

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger CI/CD on (e.g., master, main, etc.)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Replace with your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 172.31.19.96
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            scp -r . ubuntu@172.31.19.96:/home/ubuntu/ok-backend
            ssh ubuntu@172.31.19.96 'source /home/ubuntu/venv/bin/activate && cd /home/ubuntu/ok-backend && gunicorn --workers 3 --bind unix:ok-backend.sock config.wsgi:application'
            ssh ubuntu@172.31.19.96 'sudo systemctl restart nginx'
